import {StyleSheet, Platform} from 'react-native';
import FontSize from '../../../utils/common/FontsSize';
import {
  BackGround,
  ScreenWidth,
  Theme,
  White,
  FontFamily,
  LightGray,
  Shadow,
  White5,
  BackGroundColor,
  Black,
  ButtonColor,
  ScreenHeight,
} from '../../../utils/common';
import {Dimensions} from 'react-native';
export const {width, height} = Dimensions.get('screen');

const horizontalPadding = 15;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BackGround,
  },
  viewStyle: {
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: White,
  },
  imageStyle: {
    height: 40,
    width: 300,
  },
  propertyTitle: {
    fontFamily: FontFamily.Mont.Bold,
    color: Theme,
    fontSize: 22,
    padding: 20,
    paddingLeft: 30,
    alignSelf: 'flex-start',
  },
  image: {
    marginLeft: 15,
    borderRadius: 15,
    width: ScreenWidth - horizontalPadding * 2,
    height: ScreenWidth * 0.35,
    zIndex: 1,
  },
  flatListContainer: {
    paddingTop: 5,
    backgroundColor: White5,
  },
  viewItemContainer: {
    marginBottom: 20,
  },
  unitContainer: {
    marginTop: -15,
    marginHorizontal: 15,
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    shadowColor: Shadow,
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 3,
  },
  ownerName: {
    fontSize: FontSize(16),
    fontFamily: FontFamily.Mont.Bold,
    color: Theme,
    marginLeft: 15,
    marginTop: 35,
  },
  ownerAddress: {
    fontSize: FontSize(13),
    fontFamily: FontFamily.Mont.Regular,
    color: Theme,
    marginLeft: 15,
    marginTop: 5,
    marginBottom: 15,
    lineHeight: 25,
  },
  ownerDateTime: {
    fontSize: FontSize(13),
    fontFamily: FontFamily.Mont.Regular,
    color: Theme,
    marginLeft: 15,
    marginTop: 20,
  },
  infoContainer: {
    flexDirection: 'row',
    flex: 1,
    marginTop: 15,
    marginHorizontal: 20,
    marginBottom: 15,
  },
  childInfoContainer: {
    flex: 1,
  },
  unitHeaderText: {
    fontSize: FontSize(12),
    fontFamily: FontFamily.Mont.Light,
    color: Theme,
    textAlign: 'center',
  },
  unitValueText: {
    fontSize: FontSize(13),
    fontFamily: FontFamily.Mont.SemiBold,
    color: Theme,
    textAlign: 'center',
    marginTop: 10,
  },
  headerContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  headerOption: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LightGray,
    borderRadius: 13,
  },
  headerIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  headerTitle: {
    fontFamily: FontFamily.Mont.SemiBold,
    fontSize: FontSize(19),
    color: Theme,
    alignSelf: 'center',
  },
  viewParentContainer: {
    display: 'flex',
    marginTop: height * 0.12,
    backgroundColor: BackGroundColor,
  },
  upperItem: {
    width: ScreenWidth / 1.07,
    borderRadius: 30,
    //marginLeft: 20,
    backgroundColor: BackGroundColor,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  upperItemAuditor: {
    width: ScreenWidth / 1.14,
    borderRadius: 30,
    //marginLeft: 20,
    backgroundColor: BackGroundColor,
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  lowerItem: {
    marginBottom: height * 0.07,
  },
  unitHeader: {
    fontSize: 18,
    fontWeight: '600',
    alignSelf: 'flex-start',
    marginLeft: 20,
  },
  unitList: {
    padding: 15,
    margin: 5,
  },
  selectedUnit: {
    textTransform: 'capitalize',
    borderRadius: 25,
    backgroundColor: White,
    opacity: 0.7,
  },
  unitListText: {
    textTransform: 'capitalize',
    fontSize: FontSize(13),
    color: Black,
    fontFamily: FontFamily.Mont.Light,
  },
  selectedUnitText: {
    textTransform: 'capitalize',
    fontSize: FontSize(13),
    color: Black,
    fontFamily: FontFamily.Mont.SemiBold,
  },
  emptyList: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
  },
  emptyListText: {
    fontSize: 18,
    color: Theme,
    justifyContent: 'center',
    alignItems: 'center',
    lineHeight: 30,
    marginTop: 30,
  },
  emptyListTextAgain: {
    fontSize: 18,
    color: Theme,
    justifyContent: 'center',
    alignItems: 'center',
    lineHeight: 30,
  },
  emptyImage: {
    width: 250,
    height: 150,
    alignItems: 'center',
    marginLeft: 25,
  },
  loader: {
    height: '70%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  appointmentTag: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  refreshIcon: {
    width: 45,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: White,
    borderRadius: 13,
    marginTop: 10,
    marginRight: 50,
  },
  refreshIconImage: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
});
