import {StyleSheet} from 'react-native';
import {
  ScreenWidth,
  FontFamily,
  DarkGreyUnit,
  ThemeOpacity,
  ThemeOpacity8,
  Theme,
  BorderColor,
  ButtonColor,
  Black,
} from '../../../utils/common';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerStyle: {
    position: 'absolute',
    left: 0,
    marginTop: 10,
    marginLeft: 10,
    top: 0,
  },
  headerIcon: {
    height: 35,
    width: 35,
  },
  kfImage: {
    height: 40,
    width: 40,
  },
  image: {
    height: 300,
  },
  detailModal: {
    backgroundColor: 'white',
    height: '100%',
    width: '100%',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    elevation: 2,
    bottom: 40,
  },
  unitDetailView: {
    paddingHorizontal: 20,
  },
  indicatorHandle: {
    width: 75,
    height: 5,
    backgroundColor: DarkGreyUnit,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 20,
  },
  unitDetailText: {
    fontSize: 20,
    color: Theme,
    fontFamily: FontFamily.Mont.Bold,
    marginTop: 25,
  },
  appointMentAlreadyText: {
    fontSize: 16,
    color: Theme,
    fontFamily: FontFamily.Mont.Regular,
    marginTop: 15,
  },
  checkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  checkImage: {
    width: 22,
    height: 22,
  },
  yesText: {
    fontSize: 16,
    fontFamily: FontFamily.Mont.SemiBold,
    marginLeft: 10,
    color: Theme,
  },
  timeText: {
    fontSize: 16,
    color: Theme,
    fontFamily: FontFamily.Mont.SemiBold,
    marginTop: 15,
  },
  border: {
    height: 0.8,
    backgroundColor: BorderColor,
    marginVertical: 25,
  },
  srNoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
  },
  srNo: {
    fontSize: 14,
    fontFamily: FontFamily.Mont.Regular,
    color: ThemeOpacity,
  },
  srNoText: {
    fontSize: 16,
    fontFamily: FontFamily.Mont.SemiBold,
    color: Theme,
    marginTop: 10,
  },
  levelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  badContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
  },
  furnishedContainer: {
    marginTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pricingContainer: {
    marginTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  realtorContainer: {
    marginTop: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  furnishedText: {
    fontSize: 18,
    fontFamily: FontFamily.Mont.Regular,
    color: Black,
  },
  pricingText: {
    fontSize: 18,
    fontFamily: FontFamily.Mont.Regular,
    color: Black,
  },
  pricingDesc: {
    fontSize: 18,
    fontFamily: FontFamily.Mont.SemiBold,
    color: Black,
  },
  ownerContainer: {
    height: 80,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: BorderColor,
    marginVertical: 10,
    marginTop: 40,
  },
  ownerTitle: {
    color: ThemeOpacity8,
    fontSize: 16,
    fontFamily: FontFamily.Mont.Regular,
  },
  ownerName: {
    color: Theme,
    fontSize: 18,
    fontFamily: FontFamily.Mont.SemiBold,
    marginTop: 10,
  },
  ownerEmail: {
    color: ThemeOpacity8,
    fontSize: 16,
    fontFamily: FontFamily.Mont.Regular,
  },
  ownerPhone: {
    color: ThemeOpacity8,
    fontSize: 16,
    fontFamily: FontFamily.Mont.Regular,
    marginTop: 15,
  },
  ownerImage: {
    width: 40,
    height: 40,
    borderRadius: 40,
  },
  keyText: {
    fontSize: 20,
    fontFamily: FontFamily.Mont.Bold,
    color: Theme,
  },
  notes: {
    fontSize: 20,
    fontFamily: FontFamily.Mont.Bold,
    color: Theme,
    paddingHorizontal: 20,
  },
  notesDes: {
    paddingHorizontal: 20,
    marginTop: 20,
    lineHeight: 20,
    fontSize: 14,
    fontFamily: FontFamily.Mont.Regular,
  },
  startAppointMentBtn: {
    backgroundColor: ButtonColor,
    height: 50,
    borderRadius: 25,
    elevation: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginHorizontal: 20,
  },
  btText: {
    fontSize: 17,
    color: 'white',
    fontFamily: FontFamily.Mont.Bold,
  },
  keyFeatureContainer: {
    marginTop: 10,
    paddingHorizontal: 20,
  },
  keyFeatureSeparator: {paddingLeft: 10},
  keyFeatureItemView: {
    width: ScreenWidth * 0.38,
    backgroundColor: '#D9FAEB',
    borderRadius: 10,
    paddingLeft: 10,
    padding: 15,
  },
  kfIamge: {
    width: 45,
    height: 45,
  },
  kfText: {
    fontSize: 15,
    color: 'black',
    marginTop: 15,
    fontFamily: FontFamily.Mont.Regular,
    maxWidth: '90%',
    lineHeight: 18,
  },
  blindTitle: {
    color: Theme,
    fontSize: 18,
    fontFamily: FontFamily.Mont.SemiBold,
    marginBottom: 20,
  },
  buttonselection: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioButton: {
    height: 26,
    width: 26,
    borderRadius: 15,
    borderWidth: 0.2,
    borderColor: '#1D2B41',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedRadio: {
    height: 16,
    width: 16,
    borderRadius: 10,
    backgroundColor: '#7763DC',
  },
  radioName: {
    color: ThemeOpacity8,
    fontSize: 16,
    fontFamily: FontFamily.Mont.Regular,
    marginLeft: 10,
  },
});
